spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-eshop
    username: postgres
    password: e2596781234

  flyway:
    baseline-on-migrate: true
  main:
    allow-circular-references: true

